### ISSUE TITLE
Fix "The S3 bucket that you specified for CloudFront logs does not enable ACL access"

### ISSUE THREAD

**Issue by douglasnaphas** [douglasnaphas/madliberation#541]
https://github.com/douglasnaphas/madliberation/actions/runs/4911498707/jobs/8769584703

```
 ❌  DouglasnaphasMadliberation511-seal-webapp failed: Error: The stack named DouglasnaphasMadliberation511-seal-webapp failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Invalid request provided: AWS::CloudFront::Distribution: The S3 bucket that you specified for CloudFront logs does not enable ACL access: douglasnaphasmadliberati-distrologgingbucketcf515-151bvmwsy5lm7.s3.us-east-1.amazonaws.com (Service: CloudFront, Status Code: 400, Request ID: cd7f682e-7526-464f-8fdc-599dffd9e13a)" (RequestToken: d3c3c79c-3969-fa2c-d1b1-ece62a801f19, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/home/runner/work/madliberation/madliberation/infra/node_modules/aws-cdk/lib/index.js:397:10236)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async deployStack2 (/home/runner/work/madliberation/madliberation/infra/node_modules/aws-cdk/lib/index.js:400:145739)
    at async /home/runner/work/madliberation/madliberation/infra/node_modules/aws-cdk/lib/index.js:400:128776
    at async run (/home/runner/work/madliberation/madliberation/infra/node_modules/aws-cdk/lib/index.js:400:126782)
```

**Comment by douglasnaphas** [comment]
Not getting this error any more, closing.
